language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add myconfig.ini; fi;'
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer self-update
  - composer update

script: phpunit --coverage-clover=coverage.clover

services:
  - mongodb
  - redis-server

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
